services:
  - type: web
    name: notepadfy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: notepadfy_db
          property: connectionString
      - key: NEXT_PUBLIC_SITE_URL
        value: https://notepadfy.com
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: notepadfy_db
    databaseName: notepadfy
    user: notepadfy 